From tensorflow/tensorflow:2.10.0-gpu-jupyter

RUN pip install jupyterlab

### docker run --rm -p 9999:9999 --name tf-anil -it --gpus all --volume //c/users/anil1/myprojects:/MyProjects tf-anil bash
### jupyter lab --ip=0.0.0.0 --port=9999 --allow-root (didnt work)
### jupyter notebook --ip=0.0.0.0 --port=9999 --allow-root